lesson-05
Akalaimakalai/qna pull request #1
Opened 2019-11-12 02:29 UTC by Akalaimakalai

1. Реализовать следующие истории, начиная с acceptance-тестов (если они уже реализованы, покрыть acceptance-тестами):
  - Пользователь может создавать вопрос
  - Пользователь может просматривать список вопросов
  - Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу)
  - Пользователь может просматривать вопрос и ответы к нему.

 2. Добавить аутентификацию к проекту, покрыть acceptance-тестами следующие сценарии:
  - Пользователь может войти в систему
  - Пользователь может выйти из системы
  - Пользователь может зарегистрироваться в системе

 3. Реализовать следующие истоиии:
  - Только аутентифицированный пользователь может создавать вопросы и ответы
  - Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ

2019-11-12 09:56 UTC, aishek requested changes

2019-11-12 09:56 UTC, aishek commented on app/controllers/answers_controller.rb
> +      redirect_to @question, alert: "Save was not successful"
По условиям задачи тут нужно остаться на странице вопроса

2019-11-12 09:56 UTC, aishek commented on app/controllers/questions_controller.rb
> +    if current_user == @question.user
Тут нужно использовать проверку авторства методом

2019-11-12 09:56 UTC, aishek commented on app/helpers/application_helper.rb
> +  end
Нужно иметь такую проверку везде где есть пользователь. Одна из возможных реализаций — поместить метод в модель пользователя. И юнит-тесты не забыть

2019-11-12 09:56 UTC, aishek commented on spec/features/answers/create_spec.rb
> +    expect(page).to_not have_content 'Add answer'
Нужно не `have_content` а более специфичный селектор — кнопку или ссылку — ведь может быть и просто такой текст на странице, например

2019-11-12 09:56 UTC, aishek commented on spec/features/questions/create_spec.rb
> +    expect(page).to_not have_content 'Ask question'
Нужно не `have_content` а более специфичный селектор — кнопку или ссылку — ведь может быть и просто такой текст на странице, например

2019-11-12 09:56 UTC, aishek commented on spec/features/questions/destroy_spec.rb
> +      expect(page).to_not have_content('Delete question')
Нужно не `have_content` а более специфичный селектор — кнопку или ссылку — ведь может быть и просто такой текст на странице, например

2019-11-12 09:56 UTC, aishek commented on spec/features/questions/destroy_spec.rb
> +      expect(page).to_not have_content('Delete question')
Нужно не `have_content` а более специфичный селектор — кнопку или ссылку — ведь может быть и просто такой текст на странице, например

2019-11-12 09:56 UTC, aishek commented on spec/features/questions/index_spec.rb
> +    questions.each do |q|
Не надо сокращать имя переменной

2019-11-12 09:56 UTC, aishek commented on spec/features/questions/show_spec.rb
> +    expect(page).to have_content(answers[2].body)
Просится в цикл

2019-11-12 09:56 UTC, aishek commented on spec/features/sign_out_spec.rb
> +  scenario 'user tries to sign out' do
Что с гостем?

2019-11-12 09:56 UTC, aishek commented on spec/features/sign_up_spec.rb
> +  scenario 'user tries to sign up' do
Надо ошибки тоже проверить

2019-11-12 09:56 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +      before { login(user) }
И неавтора нужно проверить

2019-11-12 09:56 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +      before { login(user) }
И неавтора проверить нужно

2019-11-12 09:56 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +      before { login(user) }
И неавтора проверить

2019-11-13 15:57 UTC, aishek requested changes

2019-11-13 15:57 UTC, aishek commented on app/controllers/answers_controller.rb
> +      redirect_to @question, alert: errors
Такой трюк не пройдёт. Надо `render 'questions/show'` да и всё

2019-11-13 15:57 UTC, aishek commented on app/helpers/application_helper.rb
> +  end
Во вьюшках достаточно проверки `current_user&.is_author?`, а этот хелпер не нужен

2019-11-13 15:57 UTC, aishek commented on app/models/question.rb
> +  end
Метод повторяется. Что если вынести его в модель пользователя?

2019-11-13 15:57 UTC, aishek commented on spec/models/question_spec.rb
> +          expect(question.is_author?(user)).to be_truthy
Такое лучше записывать в форме https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/predicate-matchers

2019-11-13 15:57 UTC, aishek commented on spec/models/question_spec.rb
> +          expect(question.is_author?(user)).to be_falsey
Такое лучше записывать в форме https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/predicate-matchers

2019-11-13 15:57 UTC, aishek commented on spec/features/questions/index_spec.rb
> +  given!(:questions) { create_list(:question, 3, user: user) }
Чем меньше сущностей создаётся при прогоне теста, тем быстрее проходит тест. Тут достаточно создать два вопроса

2019-11-14 18:30 UTC, aishek requested changes
В целом уже всё хорошо, но хочется ещё больше внимания к деталям.

2019-11-14 18:30 UTC, aishek commented on app/models/user.rb
> +    object.user == self
Задание со звёздочкой: избежать тут дополнительного запроса в базу

2019-11-14 18:30 UTC, aishek commented on spec/models/user_spec.rb
> +          expect(user.is_author?(question)).to eq true
Такое лучше записывать в форме https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/predicate-matchers

2019-11-14 18:30 UTC, aishek commented on spec/models/user_spec.rb
> +          expect(user.is_author?(question)).to eq false
Такое лучше записывать в форме https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/predicate-matchers

2019-11-14 18:30 UTC, aishek commented on spec/models/user_spec.rb
> +          question = create(:question)
Для подобного лучше использовать `let`

2019-11-14 18:30 UTC, aishek commented on spec/models/user_spec.rb
> +          question = create(:question, user: user)
Для подобного лучше использовать `let`

2019-11-14 18:30 UTC, aishek commented on spec/models/user_spec.rb
> +  describe 'model methods tests' do
Можно без этого дескрайба-обёртки

2019-11-14 18:30 UTC, aishek commented on app/models/answer.rb
> +  belongs_to :user
Для этой строки нужен тест

2019-11-14 18:30 UTC, aishek commented on spec/features/answers/create_spec.rb
> +      expect(page).to have_content('Answer text')
Идеально проверить что до создания ответа такого контента не было

2019-11-14 19:30 UTC, Akalaimakalai commented on app/models/answer.rb
> +  belongs_to :user
в этом коммите https://github.com/Akalaimakalai/qna-5-/commit/62ff9247c189d5a4ae9562a6f257d5bc944122dc#diff-a68a7982922073b9602c0fd6097e0bd2
вот этот файл https://github.com/Akalaimakalai/qna-5-/blob/lesson-05/spec/models/answer_spec.rb

2019-11-15 06:33 UTC, aishek approved these changes
Решение хорошее.

Если получиться дописать юнит-тесты авторства — будет вообще идеально.

2019-11-15 06:33 UTC, aishek commented on spec/models/user_spec.rb
> +  end
Ни тот, ни другой :)

А какой-то такой `expect(user).to be_is_author(question)` согласно https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/predicate-matchers

2019-11-16 18:23 UTC, merged