Lesson 12
Akalaimakalai/qna pull request #12
Opened 2020-01-17 23:50 UTC by Akalaimakalai

Для тех, кто не использовал CanCanСan и не знаком с ним: Реализовать все проверки в проекте на наличие прав (например, такие, что только автор может редактировать вопрос/ответ и другие правила авторизации) у пользователя через CanCan, покрыть тестами класс Ability.

2020-01-18 18:15 UTC, aishek requested changes

2020-01-18 18:15 UTC, aishek commented on app/controllers/application_controller.rb
> +  # check_authorization
Закомментированный код нужно удалять

2020-01-18 18:15 UTC, aishek commented on app/models/ability.rb
> +  def admin_abilities
Тут можно вызвать `guest_abilities`, чтобы показать что админ это гость и кое-что ещё

2020-01-18 18:15 UTC, aishek commented on app/models/ability.rb
> +    can :read, :all
Тут лучше вызвать `guest_abilities`

2020-01-18 18:15 UTC, aishek commented on app/models/ability.rb
> +      vote.votable.user_id != user.id
Тут и далее лучше сравнивать объекты

2020-01-18 18:15 UTC, aishek commented on spec/factories/answers_factory.rb
> +      ActiveStorage::Current.host = 'localhost:3000'
Зачем это тут?

2020-01-18 18:15 UTC, aishek commented on spec/factories/questions_factory.rb
> +      ActiveStorage::Current.host ||= 'localhost:3000'
Подобной настройке место в конфигурации

2020-01-18 18:15 UTC, aishek commented on spec/models/ability_spec.rb
> +    let(:user_question) { create(:question, user: user) }
Для ускорения тестов можно некоторые сущности не сохранять в базу, а оставлять только в памяти с помощью `build`

2020-01-19 15:13 UTC, Akalaimakalai commented on app/models/ability.rb
> +      vote.votable.user_id != user.id
А в примечаниях к уроку, говорили наоборот.
"В самом классе Ability в правилах на редактирование, где указывается { user: user } лучше использовать конструкцию { user_id: user.id }, чтобы не делать лишний запрос к ассоциации. Это же касается и примера с Pundit: сравнивать лучше по user_id"
Как я понимаю срвнение объекто точнее, но дольше, а сравнение id быстрее, но примитивнее. Или есть ещё какие-то аспекты для приоретета к сравнению объектов? Или особености работы программ, например как в тестах мы в поля id передаём целый объект, а тесты сами понимают, что нужно использовать только id?

2020-01-19 18:47 UTC, aishek approved these changes

2020-01-19 18:47 UTC, aishek commented on app/controllers/files_controller.rb
> +  before_action :set_file
Самое интересное, что без этого хука читабельнее и проще

2020-01-19 18:47 UTC, aishek commented on app/controllers/links_controller.rb
> +  before_action :set_link, only: %i[ destroy ]
Тут без коллбека тоже читабельнее

2020-01-19 18:47 UTC, aishek commented on app/models/ability.rb
> +      vote.votable.user_id != user.id
Сравнение объектов даёт более высокий уровень абстракции. Не нужно помнить как именно они там сравниваются. И как правило к моменту проверки прав все объекты уже загружены, и новых запросов в базу не будет. В этом смысле я считаю сравнение по идентификатору микрооптимизацией.

Но в общем случае сравнение по идентификатору быстрее.

В общем замечание снимается.

2020-01-19 18:55 UTC, Akalaimakalai commented on app/controllers/files_controller.rb
> +  before_action :set_file
без этого коллбэка авторизация не отрабатывает правильно, как я понял из-за того как раз что не установлен объект по которому будет совершаться проверка прав

2020-01-21 16:06 UTC, merged