Lesson 14
Akalaimakalai/qna pull request #14
Opened 2020-01-29 03:12 UTC by Akalaimakalai

Реализовать следующие истории, используя фоновые задачи:

-Отправка ежедневного письма-дайджеста всем пользователям. Дайджест содержит список всех вопросов, созданных за последние сутки
-Автор вопроса получает уведомление на email при появлении нового ответа на свой вопрос
-Любой залогиненный пользователь может подписаться на обновления вопроса. При этом он будет получать уведомления по email при появлении новых ответов на этот вопрос. Кол-во вопросов, на которые может быть подписан пользователь не ограничено.
-Пользователь может отписаться от получения уведомлений об обновлении вопроса, если он на них подписан. Отписаться можно только от вопроса, на обновления которого пользователь подписан.
-Автор вопроса также может отписаться от получения уведомлений о новых ответах на его вопрос

2020-01-29 07:58 UTC, aishek requested changes

2020-01-29 07:58 UTC, aishek commented on app/controllers/subscriptions_controller.rb
> +  before_action :find_subscription, only: %i[ destroy ]
Если избавиться от коллбека, и поиск нужной подписки поместить в методе удаления, то код станет сильно проще.

2020-01-29 07:58 UTC, aishek commented on app/controllers/subscriptions_controller.rb
> +    @subscription.save!
Очень сложно. Лучше на уровне валидаций модели проверить что подписки ещё нет. На уровне интерфейса можно вообще никак не реагировать на эту ошибку. Так как ссылка для создания подписки будет показана только в случае, если подписки ещё нет.

2020-01-29 07:58 UTC, aishek commented on app/models/question.rb
> +  before_create :add_author_to_followers
Если написть без метода, сразу блоком, то будет понятнее. И кода будет меньше

2020-01-29 07:58 UTC, aishek commented on app/models/question.rb
> +  has_many :followers, through: :subscriptions, source: :user
Я бы выбирал созвучное название к подпискам. Например `subscribers`

2020-01-29 07:58 UTC, aishek commented on app/models/question.rb
> +  scope :yesterday, -> { where(created_at: (1.day.ago..Time.zone.now)) }
Без скоупа будет понятнее: `Question.where(created_at: 1.day.ago.all_day)`

2020-01-29 07:58 UTC, aishek commented on app/models/answer.rb
> +    NotificationService.new.new_answer_for(question)
А зачем тут создание экземпляра с помощью `new`?

2020-01-29 07:58 UTC, aishek commented on app/services/daily_digest_service.rb
> +    User.find_each(batch_size: 500) do |user|
Лучше значение `batch_size` без особой причины не менять

2020-01-29 07:58 UTC, aishek commented on app/services/daily_digest_service.rb
> +  def send_digest
Как сработает этот алгоритм, когда за вчера не было новых ответов?

2020-01-29 07:58 UTC, aishek commented on app/services/notification_service.rb
> +    question.followers.each do |user|
Тут тоже следует использовать `find_each`

2020-01-29 07:58 UTC, aishek commented on app/services/notification_service.rb
> +  def new_answer_for(question)
Логичнее сразу и ответ слать в письме

2020-01-29 07:58 UTC, aishek commented on config/schedule.rb
> +  runner "DailyDigestJob.perform_now"
Почему тут сразу сервис не вызывать?

2020-01-29 07:58 UTC, aishek commented on app/models/user.rb
> +  has_many :subs, through: :subscriptions, source: :question
Странный идентификатор. Почему не `subscribed_to_questions` например?

2020-01-29 07:58 UTC, aishek commented on spec/controllers/subscriptions_controller_spec.rb
> +        it 'rensers template :create' do
Опечатка

2020-01-29 07:58 UTC, aishek commented on spec/controllers/subscriptions_controller_spec.rb
> +      context 'is not following question yet' do
Тут бы ещё проверить атрибуты только что созданной подписки

2020-01-29 07:58 UTC, aishek commented on spec/features/questions/add_medal_spec.rb
> +    sleep(2)
Должно работать без этого

2020-01-29 07:58 UTC, aishek commented on spec/mailers/daily_digest.rb
> +RSpec.describe DailyDigestMailer, type: :mailer do
Лучше тесты написать

2020-01-29 07:58 UTC, aishek commented on spec/mailers/notification.rb
> +RSpec.describe NotificationMailer, type: :mailer do
Лучше тесты написать

2020-01-29 07:58 UTC, aishek commented on spec/models/question_spec.rb
> +  describe "scope :yesterday" do
Это фактически тестирование кода фреймворка, а он уже протестирован

2020-01-29 07:58 UTC, aishek commented on app/models/question.rb
> +  before_create :add_author_to_followers
И тесты на это поведение нужны

2020-01-29 07:58 UTC, aishek commented on spec/models/user_spec.rb
> +    it 'finds subscription' do
И на негативный случай хорошо бы иметь тест

2020-01-29 07:58 UTC, aishek commented on spec/models/user_spec.rb
> +    it 'proofs that user is following question' do
И на негативный случай хорошо бы иметь тест

2020-01-29 07:58 UTC, aishek commented on spec/services/notification_service_spec.rb
> +    question.followers.each { |user| expect(NotificationMailer).to receive(:new_answer).with(question, user).and_call_original }
А тут подписчики точно есть? И хорошо бы добавить проверку что неподписчики не получат письма.

2020-01-29 07:58 UTC, aishek commented on app/jobs/daily_digest_job.rb
> +    DailyDigestService.new.send_digest
Зачем тут создание экземпляра класса сервиса?

2020-01-29 19:52 UTC, Akalaimakalai commented on app/models/question.rb
> +  has_many :followers, through: :subscriptions, source: :user
ну follower бонально проще звучит, а в каком-нибудь "Subscriber unsubscribe subscription to question"

2020-01-29 20:09 UTC, Akalaimakalai commented on app/models/answer.rb
> +    NotificationService.new.new_answer_for(question)
Ну до этого на уроках мы всегда создавали новые инстансы сервисов при обращеении к ним, поэтому и сделал так.

2020-01-29 20:52 UTC, Akalaimakalai commented on config/schedule.rb
> +  runner "DailyDigestJob.perform_now"
Код из скрнкаста, наверное демонстрация Job'ов

2020-01-30 01:48 UTC, Akalaimakalai commented on spec/features/questions/add_medal_spec.rb
> +    sleep(2)
на деле работаетчерез раз, иногда просто не успевает загрузится в storage

2020-01-30 07:46 UTC, aishek commented on spec/features/questions/add_medal_spec.rb
> +    sleep(2)
Тогда твоя стратегия может быть такой: сделать так, чтобы direct upload как-то отображал факт своего успешного окончания на странице (если он уже так не делает), проверять это в тесте, затем только кликать на кнопку

2020-01-30 07:55 UTC, aishek requested changes

2020-01-30 07:55 UTC, aishek commented on app/controllers/subscriptions_controller.rb
> +    @subscription = Subscription.create(user_id: current_user.id, question_id: @question.id)
Если передавать объекты, то уровень сложности снижается: `@subscription = Subscription.create(user: current_user, question: @question)`

2020-01-30 07:55 UTC, aishek commented on app/models/question.rb
> +  has_many :followers, through: :subscriptions, source: :user
Я ок с этим, просто как рекомендацию.

2020-01-30 07:55 UTC, aishek commented on app/jobs/daily_digest_job.rb
> +class DailyDigestJob < ApplicationJob
Теперь этот класс нигде не используется

2020-01-30 07:55 UTC, aishek commented on spec/controllers/subscriptions_controller_spec.rb
> +          expect(Subscription.last.user).to eq user
`Subscription.last` иногда может возвращать не последнюю созданную запись. Лучше явно отсортировать по дате создания и выбрать нужную

2020-01-30 07:55 UTC, aishek commented on spec/mailers/daily_digest_spec.rb
> +    let!(:question) { create(:question, created_at: Time.zone.now - 1000) }
Есть всякие крутые штуки типа `1.hour.ago`

2020-01-30 07:55 UTC, aishek commented on spec/models/question_spec.rb
> +      expect(question.followers.first).to eq user
Можно убить сразу двух зайцев: `expect(question.followers).to eq([user])`

2020-01-30 07:55 UTC, aishek commented on spec/services/daily_digest_spec.rb
> +  it 'sends daily digest to all users' do
И нужен тест на случай когда вопросов за вчера не было

2020-01-30 14:54 UTC, aishek approved these changes

2020-01-30 14:54 UTC, aishek commented on spec/controllers/subscriptions_controller_spec.rb
> +          expect(Subscription.order(created_at: :asc).last.user).to eq user
Лучше сэкономить на запросах конечно:

```ruby
created_subscription = Subscription.order(created_at: :asc).last
expect(created_subscription).to eq question
expect(created_subscription).to eq user
```

2020-01-30 14:54 UTC, aishek commented on spec/services/daily_digest_spec.rb
> +      expect(DailyDigestService.send_digest).to be_nil
Проверка неудачная. Лучше проверить что мэйлер не вызывался вообще

2020-01-31 18:31 UTC, merged