Lesson 15
Akalaimakalai/qna pull request #15
Opened 2020-02-03 06:11 UTC by Akalaimakalai

Реализовать функцию поиска по вопросам, ответам, комментариям и пользователям. 
Должна быть возможность совершить общий поиск, сразу по всем возможным объектам, а также возможность поиска отдельно по вопросам/ответам/комментариям/пользователям.

2020-02-03 06:29 UTC, aishek requested changes
Фича-тест понятный и читабельный. К остальному есть пожелания

2020-02-03 06:29 UTC, aishek commented on app/controllers/search_controller.rb
> +class SearchController < ApplicationController
Сейчас класс делает две вещи: принимает запрос от пользователя, и содержит логику поиска. Что если поиск нужно будет вызвать не из контроллера, например?

2020-02-03 06:29 UTC, aishek commented on app/controllers/search_controller.rb
> +    @results = ThinkingSphinx.search(params[:search], classes: [find_class])
Поисковый запрос нужно эскейпить

2020-02-03 06:29 UTC, aishek commented on app/views/shared/_nav.html.slim
> +  = form_with url: "/search", method: :get, local: true do |f|
Нужно использовать роут-хелпер, чтобы пути задавались только в одном месте — в `routes.rb`

2020-02-03 06:29 UTC, aishek commented on app/views/shared/_nav.html.slim
> +        = f.select(:classes, options_for_select(['Везде', 'Вопросы', 'Ответы', 'Комментарии', 'Пользователи']))
Желательно избежать дублирования тут с классом

2020-02-03 06:29 UTC, aishek commented on app/views/search/index.html.slim
> +  p = render @results
Каким шаблоном рендериться каждый конкретный результат?

2020-02-03 06:29 UTC, aishek commented on spec/controllers/search_controller_spec.rb
> +      get :index, params: { search: 'test', classes: 'Везде' }
Надо бы проверить для каждого типа, и для неизвестного типа тоже

2020-02-03 09:29 UTC, Akalaimakalai commented on app/views/search/index.html.slim
> +  p = render @results
Вопросы - _question.html.slim, ответы -  _answer.html.slim и т.д.

2020-02-04 07:08 UTC, aishek requested changes

2020-02-04 07:08 UTC, aishek commented on app/controllers/search_controller.rb
> +    @results = SearchService.do_search(params[:search], params[:classes])
Несколько соображений:

- у классов сервисов есть соглашение по именованию метода-точки входа: `call`
- лучше сигнатуру описать так, чтобы она хэш на вход принимала
- параметры лучше называть самыми понятными и распространёнными `query` и `scope`

Итого получиться: `def self.call(query:, scope: nil)`

2020-02-04 07:08 UTC, aishek commented on app/services/search_service.rb
> +    return [] if user_string.delete(" ").empty? || !CLASSES.include?(search_klass)
Сложновато получилось. Что если при неправильном переданном скоупе просто искать по всему?

2020-02-04 07:08 UTC, aishek commented on app/services/search_service.rb
> +    ThinkingSphinx.search(ThinkingSphinx::Query.escape(user_string), classes: [CLASSES[search_klass]])
Лучше экранирование строки поиска и получение класса для поиска вынести в отдельные переменные. А то сейчас в одной строке аж три действия сразу.

2020-02-04 07:08 UTC, aishek commented on spec/controllers/search_controller_spec.rb
> +      expect(assigns(:results)).to eq [question, answer, comment, user]
Переменную можно не проверять, а вот рендеринг — обязательно

2020-02-04 07:20 UTC, Akalaimakalai commented on spec/controllers/search_controller_spec.rb
> +      expect(assigns(:results)).to eq [question, answer, comment, user]
всмысле, после каждого запроса рендеринг проверять?

2020-02-04 07:22 UTC, aishek commented on spec/controllers/search_controller_spec.rb
> +      expect(assigns(:results)).to eq [question, answer, comment, user]
Да, конечно. Каждый тест должен быть законченным и изолированным, как будто он не знает о существовании других.

2020-02-04 19:41 UTC, aishek approved these changes

2020-02-04 19:41 UTC, aishek commented on app/services/search_service.rb
> +  end
Без конструктора будет проще

2020-02-04 19:41 UTC, aishek commented on app/services/search_service.rb
> +    return [] if @query.delete(" ").empty?
В чём смысл этой проверки?

2020-02-04 20:44 UTC, Akalaimakalai commented on app/services/search_service.rb
> +    return [] if @query.delete(" ").empty?
просто при запросе пустой строки начинало искать всё и везде, летело куча непонятных запросов в бд, поэтому попытался сделать чтобы если юзер ничего не ввёл ничего и не искало

2020-02-05 08:02 UTC, aishek commented on app/services/search_service.rb
> +    return [] if @query.delete(" ").empty?
Я думаю можно забить пока на это нет отдельного требования — пусть ищет.

2020-02-06 01:31 UTC, merged