Lesson-06
Akalaimakalai/qna pull request #2
Opened 2019-11-17 21:08 UTC by Akalaimakalai

1. Реализовать добавление ответов к вопросам через ajax, покрыть все тестами. При этом, нужно добавлять только вновь созданный ответ к вопросу, без повторного рендеринга всего списка ответов.
2. Используя ajax, реализовать следующие истории и задачи:

  - Только автор может отредактировать свой вопрос
  - Только автор может отредактировать свой ответ
  - Переделать удаление ответов на ajax
  - Автор вопроса может выбрать лучший ответ для своего вопроса (лучший ответ может быть только 1)
  - Автор вопроса может выбрать другой ответ как лучший, если у вопроса уже выбран лучший ответ (предыдущий лучший ответ перестает быть таковым)
  - Если у вопроса выбран лучший ответ, то он отображается первым в списке ответов.

Примечания:

 - Все истории реализуем через TDD, т.е. сначала тесты.
 - Проверку на авторство по-прежнему реализуем вручную на уровне контроллеров. Это нужно тестировать как на уровне acceptance-тестов (например то, что нет ссылки на действие), так и на уровне тестов контроллера (то, что действие в действительности не выполнено).

2019-11-22 06:52 UTC, aishek requested changes
Получается неплохо.

Несколько моментов надо проработать:

- порядок следования ответов на вопрос нужно переделать через сервер с юнитами и фича-тестами
- шаблоны следует перевести на слим (несколько типов шаблонов в проекте бывают по очень веским обстоятельствам)
- меня смущает способ экономии строк в тестах, но пока не понимаю почему

2019-11-22 06:52 UTC, aishek commented on app/assets/javascripts/answers.js
> +};
Сортировка должна быть на сервере, а не на клиенте. Что если надо будет отправлять письмо с ответами на вопросы в таком же порядке?

2019-11-22 06:52 UTC, aishek commented on app/controllers/questions_controller.rb
> +  def best
Метод относится к ответу, а находится в контроллере вопросов. Для меня странно

2019-11-22 06:52 UTC, aishek commented on app/views/questions/update.js.erb
> +<% unless @question.errors.present? %>
Лучше "выпрямить" логику с помощью `if @question.errors.blank?`

2019-11-22 06:52 UTC, aishek commented on app/views/questions/_show_question.html.slim
> +- if user_signed_in? && current_user.is_author?(question)
Если я правильно понял, то это сокращается до `- if current_user&.is_author?(question)`

2019-11-22 06:52 UTC, aishek commented on app/views/questions/_question.html.erb
> +    <% if current_user.present? && current_user.is_author?(question) %>
Можно короче: `<% if current_user&.is_author?(question) %>`

2019-11-22 06:52 UTC, aishek commented on app/views/answers/update.js.erb
> +<% unless @answer.errors.present? %>
Лучше "выпрямить" логику с помощью например `if @answer.errors.empty?`

2019-11-22 06:52 UTC, aishek commented on app/views/answers/_answer.html.slim
> +  - if user_signed_in? && current_user.is_author?(answer)
Вот тут и в похожих местах вполне сокращается до `current_user&.is_author?(answer)`

2019-11-22 06:52 UTC, aishek commented on app/models/answer.rb
> +  belongs_to :best_for, class_name: 'Question', optional: true
Мне выворачивает мозг от такой ассоциации :) А ещё в теории это означает что ответ может быть для одного вопроса, а назначен лучшим для другого.

2019-11-22 06:52 UTC, aishek commented on config/routes.rb
> +  post '/questions/:id/best', to: 'questions#best'
Лучше ручного кода поменьше, а пользоваться чем-то таким https://guides.rubyonrails.org/routing.html#adding-member-routes

2019-11-22 06:52 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +          expect { delete :destroy, params: { id: answer }, format: :js }.to change(Answer, :count).by(-1)
Надо проверить ответ контроллера

2019-11-22 06:52 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +          expect { delete :destroy, params: { id: answer2 }, format: :js }.to_not change(Answer, :count)
Надо проверить ответ контроллера

2019-11-22 20:53 UTC, Akalaimakalai commented on app/views/questions/_question.html.erb
> +    <% if current_user.present? && current_user.is_author?(question) %>
при таком варианте возникает ошибка 
``` 
ActionView::Template::Error: undefined method `is_author?' for nil:NilClass
```

2019-11-22 20:55 UTC, Akalaimakalai commented on app/views/questions/_show_question.html.slim
> +- if user_signed_in? && current_user.is_author?(question)
при таком варианте возникает ошибка
```
ActionView::Template::Error: undefined method `is_author?' for nil:NilClass
```

2019-11-22 20:58 UTC, Akalaimakalai commented on app/views/answers/_answer.html.slim
> +  - if user_signed_in? && current_user.is_author?(answer)
при таком варианте возникает ошибка
```
ActionView::Template::Error: undefined method `is_author?' for nil:NilClass
```

2019-11-22 22:27 UTC, Akalaimakalai commented on app/models/answer.rb
> +  belongs_to :best_for, class_name: 'Question', optional: true
В первом варианте я использовал атрибут correct у ответа, что бы опредалять его правильность, но условие: "Может быть только один правильный ответ" - привелок тому, что приходилось постоянно ображаться к БД, обновляя correct сразу у нескольких вопросов и проверять действительно ли он там сейчас один или нет. Плюсом к этому получилось что ответ теперь отчасти может обновлять автор вопроса, а не автор ответа, что тоже неочень мне понравилось. В попытках уйти от этих дух неприятностей и было рождено это извражение.

2019-11-22 22:35 UTC, Akalaimakalai commented on app/models/answer.rb
> +  belongs_to :best_for, class_name: 'Question', optional: true
только вот теперь я думаю, что, возможно, её надо было делать в другую сторону

2019-11-23 12:22 UTC, aishek commented on app/views/questions/_show_question.html.slim
> +- if user_signed_in? && current_user.is_author?(question)
Ошибка из-за того что амперсанд пропущен: `current_user&.is_author?`

2019-11-23 12:22 UTC, aishek commented on app/views/questions/_question.html.erb
> +    <% if current_user.present? && current_user.is_author?(question) %>
Ошибка из-за того что амперсанд пропущен: `current_user&.is_author?`

2019-11-23 12:22 UTC, aishek commented on app/views/answers/_answer.html.slim
> +  - if user_signed_in? && current_user.is_author?(answer)
Ошибка из-за того что амперсанд пропущен: `current_user&.is_author?`

2019-11-23 12:25 UTC, aishek commented on app/models/answer.rb
> +  belongs_to :best_for, class_name: 'Question', optional: true
Я бы выбирал из двух вариантов:

1. завести булево поле в ответе с уникальным индексом и валидатором что идентификатор вопроса должен быть уникальным если поле `best` в ответе установлено в `true`
2. завести отдельную модель "идентификатор вопроса - идентификатор ответа" для пометки лучшего ответа также с уникальным индексом и валидатором на эту пару полей

2019-11-24 08:10 UTC, aishek requested changes
Я не могу принять реализацию лучшего ответа. Надо попробовать сделать на основе булевой колонки `best` в таблице ответов например.

2019-11-24 08:10 UTC, aishek commented on app/models/question.rb
> +  end
Удобнее подобное спрашивать у ответа

2019-11-24 08:10 UTC, aishek commented on app/models/question.rb
> +  end
Нужно постараться сделать подобное средствами базы, так будет максимально быстро работать

2019-11-24 08:10 UTC, aishek commented on spec/models/question_spec.rb
> +  describe '#sort_answers' do
Тут бы лучше взять все ответы вопроса и сравнить их с массивом в нужном порядке.

2019-11-25 07:44 UTC, aishek requested changes

2019-11-25 07:44 UTC, aishek commented on app/controllers/answers_controller.rb
> +      @answer.update(correct: true)
Это нужно поместить в модель, так как надо уметь помечать лучшим ответ не только из контроллера

2019-11-25 07:44 UTC, aishek commented on app/controllers/questions_controller.rb
> +  # end
Закомментированный код нужно удалять

2019-11-25 07:44 UTC, aishek commented on app/models/answer.rb
> +  # end
Закомментированный код нужно удалять

2019-11-25 07:44 UTC, aishek commented on app/models/answer.rb
> +  # belongs_to :best_for, class_name: 'Question', optional: true
Закомментированный код нужно удалять

2019-11-25 07:44 UTC, aishek commented on app/models/question.rb
> +  end
Это нужно сделать на уровне базы, так будет максимально быстро выполняться

2019-11-25 07:44 UTC, aishek commented on app/models/question.rb
> +  # has_one :best_answer, class_name: "Answer", foreign_key: 'best_for_id'
Закомментированный код нужно удалять

2019-11-25 07:44 UTC, aishek commented on app/models/question.rb
> +  # attr_reader :answers_list, :var_best_answer
Закомментированный код нужно удалять

2019-11-25 07:44 UTC, aishek commented on app/models/question.rb
> +  # end
Закомментированный код нужно удалять

2019-11-25 07:44 UTC, aishek commented on app/views/answers/_answer.html.slim
> +  - if answer.correct
Для булевых колонок рельса делает метод со знаком вопроса на конце, надо использовать его: `- if answer.correct?`

2019-11-25 07:44 UTC, aishek commented on config/routes.rb
> +  resources :answers do
Почему не поместить в 7 строку?

2019-11-25 07:44 UTC, aishek commented on db/schema.rb
> +    t.boolean "correct", default: false
Изменения в схеме базы данных есть, а миграции нет. Так делать не следует. И изменению структуры БД всегда должна прилагаться миграция.

2019-11-25 07:44 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +  # describe 'POST #best' do
Закомментированный код нужно удалять

2019-11-25 07:44 UTC, aishek commented on spec/features/questions/best.rb
> +# Автор вопроса может выбрать лучший ответ для своего вопроса
Мне показалось или тест дублируется?

2019-11-25 07:44 UTC, aishek commented on spec/models/answer_spec.rb
> +  # it { is_expected.to belong_to(:best_for).class_name('Question').optional }
Закомментированный код нужно удалять

2019-11-25 07:44 UTC, aishek commented on spec/models/question_spec.rb
> +  # it { should have_one(:best_answer) }
Закомментированный код нужно удалять

2019-11-25 07:44 UTC, aishek commented on spec/models/question_spec.rb
> +  # describe '#best?' do
Закомментированный код нужно удалять

2019-11-25 07:44 UTC, aishek commented on spec/models/question_spec.rb
> +    let!(:answer3) { create(:answer, question: question, created_at: Time.now - 100) }
Можно `created_at` вручную не указывать, он проставится в порядке создания автоматически

2019-11-25 07:44 UTC, aishek commented on spec/support/questions_shared_contexts.rb
> +# ---Controller---
Напишу последний раз в качестве рекомендации. Подобный подход экономит строки, но ухудшает читабельность. Ведь очень сложно подобрать точное и описательное название.

Компьютеру без разницы сколько строк, человеку лучше меньше строк при одинаковой читабельности, но ещё лучше большая читабельность даже при большем количестве строк. А программисты гораздо чаще читают код, чем пишут.

Так что или получиться сейчас отучиться от этой пагубной привычки, или следующий тимлид отучит.

2019-11-25 18:16 UTC, Akalaimakalai commented on db/schema.rb
> +    t.boolean "correct", default: false
ну миграции нет, потому что я откатился, чтобы вернуть поле correct. Подумал, зачем мне хранить миграции, которые сперва удаляют одну строку, потом возвращают её

2019-11-25 19:25 UTC, Akalaimakalai commented on spec/features/questions/best.rb
> +# Автор вопроса может выбрать лучший ответ для своего вопроса
он без _spec, так что не работал. Оставлял на всякий случай, как и закоменченый код. ну теперь удалю

2019-11-26 07:50 UTC, aishek requested changes
Остался последний рывок: поработать методы лучшего ответа и тесты к ним

2019-11-26 07:50 UTC, aishek commented on app/models/answer.rb
> +  default_scope { order(correct: :desc) }
Будет ещё лучше, если явно указать условие сортировки остальных, не лучших ответов. И для этого метода нужны юнит- и фича-тесты

2019-11-26 07:50 UTC, aishek commented on app/models/answer.rb
> +    update(correct: true)
Три соображения:

- нужно обернуть всё в транзакцию, ведь у нас сброс старого лучшего и установка нового это как бы одно действие
- нужно использовать `update!`, ведь мы не ожидаем что обновление не пройдёт, а если и так, то пусть лучше оно прямо тут сломается и мы сразу узнаем об этом
- сброс старого лучшего можно сократить до `question.answers.update_all(correct: false)` — всё равно в итоге будет изменена только одна строка

2019-11-26 20:10 UTC, aishek approved these changes

2019-11-26 20:10 UTC, aishek commented on app/models/answer.rb
> +    Answer.transaction do
Метод существует на уровне объекта класса, поэтому можно просто `transaction`

2019-11-26 20:10 UTC, aishek commented on spec/models/answer_spec.rb
> +      answer2 = create(:answer, question: question, correct: true)
Это лучше в `let!`

2019-11-26 20:10 UTC, aishek commented on spec/features/answers/best_spec.rb
> +      answer2 = create(:answer, question: question, user: user, correct: true)
Это лучше в `given`

2019-11-26 20:10 UTC, aishek commented on spec/features/answers/best_spec.rb
> +      answer2 = create(:answer, question: question, user: user, created_at: answer.created_at - 100)
Это лучше в given, а `created_at: 1.day.ago` можно например

2019-11-28 12:32 UTC, merged