Lesson 07
Akalaimakalai/qna pull request #3
Opened 2019-11-30 20:38 UTC by Akalaimakalai

Реализовать следующие истории:
 - Пользователь может добавить один или несколько файлов при создании вопроса
 - Пользователь может добавить один или несколько файлов при создании ответа
 - Автор вопроса может добавить файлы при редактировании своего вопроса
 - Автор ответа может добавить файлы при редактировании своего ответа
 - Автор вопроса может удалить любой из прикрепленных к своему вопросу файлов
 - Автор ответа может удалить любой из прикрепленных к своему ответу файлов
 - Реализовать хранение файлов через Amazon S3 (или любое другое поддерживаемое облачное хранилище) и прямую загрузку с клиента (см. edgeguides.rubyonrails.org)

2019-12-01 17:26 UTC, aishek requested changes
В целом очень хорошее и чистое решение. Значит пора переходить на следующий уровень с большим вниманием к деталям.

2019-12-01 17:26 UTC, aishek commented on app/controllers/answers_controller.rb
> +  end
Способ удаления файла не зависит от того, к какому объекту он приаттачен. Лучше завести отдельный контроллер файлов с методом удаления.

2019-12-01 17:26 UTC, aishek commented on app/controllers/questions_controller.rb
> +  end
Способ удаления файла не зависит от того, к какому объекту он приаттачен. Лучше завести отдельный контроллер файлов с методом удаления.

2019-12-01 17:26 UTC, aishek commented on app/views/answers/_answer.html.slim
> +
Просится в партиал

2019-12-01 17:26 UTC, aishek commented on app/views/questions/_show_question.html.slim
> +
Просится в партиал

2019-12-01 17:26 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +          expect(user).to be_is_author(answer_with_file)
Вот эти два действия не связаны. И в целом мне непонятно что проверяет этот тест.

2019-12-01 17:26 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        end
Мне непонятно что проверяет этот тест

2019-12-01 17:26 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        end
Вот эти два действия не связаны. И в целом мне непонятно что проверяет этот тест

2019-12-01 17:26 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        end
Это не нужно проверять, данные для теста уже построены таким образом чтобы условие выполнялось

2019-12-01 21:23 UTC, Akalaimakalai commented on spec/controllers/questions_controller_spec.rb
> +        end
Неочень понятно концептуально. Я думал если есть строчка кода, то её нужно тестить. А тут получается, что развилки мы не тестим, а лишь подстраиваемся под них?

2019-12-02 07:48 UTC, aishek approved these changes

2019-12-02 07:48 UTC, aishek commented on app/assets/javascripts/files.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
Пустые файлы нужно удалять

2019-12-02 07:48 UTC, aishek commented on app/assets/stylesheets/files.scss
> +// Place all the styles related to the files controller here.
Пустые файлы нужно удалять

2019-12-02 07:48 UTC, aishek commented on app/controllers/files_controller.rb
> +    @record = Object.const_get(@file.record_type).find(@file.record_id)
Не надо вручную, просто `@file.record` должен сработать

2019-12-02 07:48 UTC, aishek commented on app/helpers/files_helper.rb
> +module FilesHelper
Пустые файлы нужно удалять

2019-12-02 07:52 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        end
Не так. Попробую пояснить.

Есть метод контроллера, который мы не видим. И мы должны его протестировать, отправляя на вход какие-то значения, и проверяя что он возвращает, а также проверяя сайд-эффекты в базе.

И есть данные, которые мы заранее описываем в тесте, чтобы потом подавать их в метод контроллера для наших проверок. Мы их уже видим в тесте. Более того, мы сами их создали с нужными нам характеристиками. Поэтому и нет смысла их тестировать.

2019-12-03 15:54 UTC, merged