Lesson 08
Akalaimakalai/qna pull request #5
Opened 2019-12-06 21:12 UTC by Akalaimakalai

1. Реализовать следующие истории:

 - Пользователь может добавлять несколько ссылок к вопросу или ответу. 
Для реализации можно использовать gem cocoon (github.com).
   - При добавлении ссылки валидировать ее на формат URL, если ссылка не валидная, не создавать объект и выводить сообщение об ошибке валидации
   - Если дана ссылка на gist, то выводить сразу gist, а не просто ссылку.
- Автор может удалить ссылки у своего вопроса/ответа
- При редактировании  вопроса/ответа автор может добавить новые ссылки 

2. Реализовать награждение за лучший ответ:
- При создании вопроса, пользователь может также создать награду за лучший ответ, которую получит отвечающий
  - награда - это название и прикрепленное пользователем изображение
- Когда автор вопроса выбирает лучший ответ, пользователь, давший лучший ответ получает назначенную награду
- Пользователь может просматривать полученные им награды
  - При этом он видит заголовок вопроса, изображение награды и ее название

2019-12-07 07:35 UTC, aishek requested changes
Меня очень порадовали весьма читабельные фича-спеки.

Помимо прочих замечаний нужно ещё подумать как хотя бы юнит-тесты научить успешно проходить без сети.

2019-12-07 07:35 UTC, aishek commented on app/helpers/links_helper.rb
> +module LinksHelper
Пустые файлы нужно удалять

2019-12-07 07:35 UTC, aishek commented on app/helpers/medals_helper.rb
> +module MedalsHelper
Пустые файлы нужно удалять

2019-12-07 07:35 UTC, aishek commented on app/models/answer.rb
> +  has_many :links, dependent: :destroy, as: :linkable
Ассоциацию и разрешение на использование вложенных атрибутов для неё нужно положить в консерн

2019-12-07 07:35 UTC, aishek commented on app/views/answers/_answer.html.slim
> +            = link_to 'delete', link_path(link), method: :delete, remote: true
Просится в общий партиал, чтобы его можно было использовать и в вопросах, и в ответах.

2019-12-07 07:35 UTC, aishek commented on app/views/questions/_link_fields.html.slim
> +.nested-fields
Тут бы ещё кнопку на удаление

2019-12-07 07:35 UTC, aishek commented on app/views/shared/_gist.html.slim
> +p = gist.client.gist_content
Тут две проблемы.

Во-первых, вьюшка почему-то знает про клиент, хотя наличие клиента — это внутренняя особенность реализации. Объект, который знает всё про гист, это хорошо, но пусть он будет обособленным:

```ruby
class Link < ApplicationRecord
  # ...
  def gist?
    # true если ссылка похожа на ссылку на гист
  end

  def gist
    return unless gist?
    Gist.new(self)
  end
end
```

```ruby
class Link::Gist
  def initialize(link)
    # ...
  end

  def name
    # ...
  end

  def url
    # ...
  end

  def content
    # ...
  end  
end
```

```slim
- links.each do |link|
  - if link.gist?
    = render link.gist
  - else
    / ...
```

Во-вторых, каждый раз на рендре html происходит сетевой запрос. Можно перед сохранением один раз сходить по сети, забрать все данные, и сохранить их в базу например.

2019-12-07 07:35 UTC, aishek commented on spec/models/question_spec.rb
> +  it { should have_many(:links).dependent(:destroy) }
Ассоциацию ссылок и `accept_nested_attributes_for` для них нужно положить в `shared_examples`

2019-12-07 07:35 UTC, aishek commented on app/services/gist_service.rb
> +      set_content
Если заменить вызов метода на его тело в каждой из трёх строк то код станет только проще

2019-12-07 07:35 UTC, aishek commented on spec/models/answer_spec.rb
> +  it { should accept_nested_attributes_for :links }
Тут тоже не забыть использовать `shared_examples`

2019-12-07 07:35 UTC, aishek commented on spec/features/questions/edit_spec.rb
> +        expect(page).to have_link('Google', href: 'http://google.ru/')
Идеально проверить что до удаления ссылок не было на странице

2019-12-07 07:35 UTC, aishek commented on spec/features/answers/edit_spec.rb
> +        expect(page).to have_link('Google', href: 'http://google.ru/')
Идеально проверить что до удаления ссылок не было на странице

2019-12-07 07:35 UTC, aishek commented on app/controllers/links_controller.rb
> +    @record = @link.linkable
`@record` никак не используется во вьюшках, поэтому можно сделать её локальной переменной как минимум

2019-12-08 18:17 UTC, Akalaimakalai commented on app/controllers/links_controller.rb
> +    @record = @link.linkable
пришлось также удалить тест который проверял правильную установку переменной

2019-12-10 06:03 UTC, aishek requested changes
Нужно дописать юнит-тесты, это важно

2019-12-10 06:03 UTC, aishek commented on spec/models/link_spec.rb
> +RSpec.describe Link, type: :model do
Тут нужно дописать тесты на создание гиста и валидацию ссылки

2019-12-10 15:21 UTC, aishek approved these changes

2019-12-10 15:21 UTC, aishek commented on spec/models/link_spec.rb
> +        expect(link_with_gist.gist).to_not be_nil
Идеально сделать бы чтобы тоже без сети работало. Ну и атрибуты поточнее проверить.

2019-12-11 20:42 UTC, merged