Lesson 09
Akalaimakalai/qna pull request #6
Opened 2019-12-14 16:24 UTC by Akalaimakalai

Используя JSON, реализовать следующие истории:
 

 - Аутентифицированный пользователь может голосовать за понравившийся вопрос/ответ
 - Пользователь не может голосовать за свой вопрос/ответ
 - Пользователь может проголосовать "за" или "против" конкретного вопроса/ответа только один раз (нельзя голосовать 2 раза подряд "за" или "против")
 - Пользователь может отменить свое решение и после этого переголосовать.
 - У вопроса/ответа должен выводиться результирующий рейтинг (разница между голосами "за" и "против")

При реализации голосования запрещено использовать сторонние гемы для этого функционала

Рекомендации:
 - Посмотреть мастер-класс "Rails Concerns" (ссылка в дополнительных материалах к уроку) и реализовать возможность голосования через консерны.

2019-12-17 20:38 UTC, aishek requested changes
В решении очень хорошо наличие архитектурной идеи.

К сожалению, у неё есть проблемы с обеспечением целостности данных — я смогу проголосовать несколько раз. Чтобы их решить, надо много кода написать "вручную". 

Предлагаю максимум работы возложить на базу данных: пусть она проверяет что кто-то проголосовал один раз. Для этого нужна модель голоса со ссылками на цель голосования, пользователя и со значением голосования. Если к ней сделать уникальный индекс по цели и пользователю, то физически два голоса будет не подать. Рейтинг цели будет рассчитываться как сумма значений голосов за цель. Чтобы не писать вручную отмену голоса, можно постановить что голосование удаляет все предыдущие голоса пользователя за цель. Наконец метод в контроллере голосования можно сделать только один — классический `create`.

2019-12-17 20:38 UTC, aishek commented on app/assets/javascripts/answers.js
> +  //   });
Закомментированный код нужно удалять

2019-12-17 20:38 UTC, aishek commented on app/assets/javascripts/questions.js
> +  console.log(score);
Отладочный код нужно удалять

2019-12-17 20:38 UTC, aishek commented on app/controllers/answers_controller.rb
> +    # end
Закомментированный код нужно удалять

2019-12-17 20:38 UTC, aishek commented on config/routes.rb
> +      put 'revote'
Зачем разными http-методами объявлять разные методы контроллеров?

2019-12-17 20:38 UTC, aishek commented on app/models/question.rb
> +  after_save :create_score
Код про голосование похож — надо подумать насчёт того, чтобы вынести его в консёрн

2019-12-17 20:38 UTC, aishek commented on app/controllers/scores_controller.rb
> +class ScoresController < ApplicationController
В этом контроллере странно что после вызова метода голосования надо ещё отдельно вызывать сохранение. Почему это не сделать в методе голосования?

2019-12-17 20:38 UTC, aishek commented on spec/models/answer_spec.rb
> +  it { should have_one(:score).dependent(:destroy) }
Тут тоже нужно подумать про использование `shared_examples` для проверок кода голосования

2019-12-18 19:37 UTC, aishek requested changes
Опять получилось на порядок сложнее чем нужно. Модель `Score` не нужна, голоса можно привязывать сразу к нужной модели.

2019-12-18 19:37 UTC, aishek commented on app/assets/javascripts/score.js
> +  $('.score-vote-link').on('ajax:success', function(e) {
Не следует сокращать имена переменных, `event` сделает код только лучше.

2019-12-18 19:37 UTC, aishek commented on app/models/concerns/scorable.rb
> +    # нужно ли всвязи с этим вносить belongs_to :user в данный консёрн?
И так, и так будет правильно. Так что можно не вносить

2019-12-21 08:30 UTC, aishek requested changes
Ещё нужно не забыть тест на то, что можно проголосовать только один раз

2019-12-21 08:30 UTC, aishek commented on app/assets/javascripts/vote.js
> +  $('.vote-link').on('ajax:success', function(e) {
Лучше в таких случаях не сокращать имя переменной

2019-12-21 08:30 UTC, aishek commented on app/controllers/questions_controller.rb
> +  before_action :load_question, only: %i[ show edit update destroy create_vote ]
Метода `create_vote` не существует же

2019-12-21 08:30 UTC, aishek commented on app/controllers/questions_controller.rb
> +  end
Насколько я понял этот метод не используется же

2019-12-21 08:30 UTC, aishek commented on app/models/vote.rb
> +  validates :value, presence: true
Ещё полезно ограничить список возможных значений для этого поля

2019-12-21 08:30 UTC, aishek commented on app/controllers/votes_controller.rb
> +    @record.sum_votes
Весь этот код можно положить в `before_create`, а сам контроллер написать в виде

```ruby
if @vote.create(...)
  render ...
else
  flash.now[:alert] = "You can't vote for youself"
end
```

2019-12-21 08:30 UTC, aishek commented on app/models/concerns/votable.rb
> +  end
Можно проще: `votes.where(user: user).delete_all`

2019-12-21 08:30 UTC, aishek commented on app/models/concerns/votable.rb
> +  end
Лучше метод назвать как-то типа `rating`, и просто с помощью https://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-sum считать рейтинг

2019-12-22 08:29 UTC, aishek requested changes

2019-12-22 08:29 UTC, aishek commented on app/models/vote.rb
> +  validates :value, presence: true
То есть `-6` тоже подойдёт?

2019-12-22 08:29 UTC, aishek commented on app/models/vote.rb
> +  end
Лучше не делать кэш — пусть база всегда возвращает пересчитанное значение. Кэш сложно обновлять, плюс надо в каждый объект, за который можно голосовать добавлять поле, это неудобно

2019-12-22 08:29 UTC, aishek commented on app/models/vote.rb
> +  after_save :count_votes
Тут лучше сразу блоком написать, будет читабельнее

2019-12-22 08:29 UTC, aishek commented on app/models/concerns/votable.rb
> +  end
Метод делает две вещи: считает сумму и присваивает поле. Лучше в подобных случаях присваивание делать снаружи. А вообще не надо счётчик нигде хранить, пусть всегда актуальное значение из базы возвращается

2019-12-22 08:29 UTC, aishek commented on spec/controllers/votes_controller_spec.rb
> +      context 'is NOT author of the record' do
А ещё тут нужно проверить ответ контроллера

2019-12-22 16:17 UTC, Akalaimakalai commented on app/models/vote.rb
> +  end
Я добовляю поле score, потому что не знаю, как перед отправкой дописать информацию в json объект?

2019-12-22 16:19 UTC, Akalaimakalai commented on spec/controllers/votes_controller_spec.rb
> +      context 'is NOT author of the record' do
вот тут у меня возникла проблема, я не знаю как правильно тестировать ответ в виде json объекта.

2019-12-23 15:55 UTC, aishek approved these changes

2019-12-23 15:55 UTC, aishek commented on spec/models/vote_spec.rb
> +RSpec.describe Vote, type: :model do
И тут хорошо бы проверить работу коллбека

2019-12-25 09:01 UTC, merged